stages:

  process_data:
    cmd: python src\training\process_data.py
    deps:
      - data/raw/train.csv
    params:
      - data
      - split
    outs:
      - data/processed/train-train.parquet
      - data/processed/train-test.parquet


  train:
    cmd: python src\training\train.py 
    deps:
      - data/processed/train-train.parquet
    params:
      - model
      - experiment
    outs:
      - models/best_model.pkl


  evaluate:
    cmd: python src\training\evaluate.py
    deps:
      - data/processed/train-test.parquet
      - models/best_model.pkl
    params:
      - model
      - experiment
    outs:
      - reports/metrics.json