  data:
    raw_path: data/raw
    processed_path: data/processed
    file_name: train
    target_column: Survived
    test_path: data/processed/train-test.parquet

  split:
    test_size: 0.45
    random_state: 12

  model:
    logistic:
      max_iter: 48
      C: 0.2

    random_forest:
      random_state: 40
      n_estimators: 19
      max_depth: 12
      min_samples_split: 12
      min_samples_leaf: 11

  experiment:
    name: my-titanic-experiments
    DAGSHUB_USERNAME: kenzy.3ab7alim
    DAGSHUB_REPO: MLOps-Labs

  output:
    model_path: models/best_model.pkl
    metrics_path: reports/metrics.json

